baseURL = 'https://0xGently.github.io/'
languageCode = 'en-us'
title = '0xGently'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"] # Arama motorunun çalışması için JSON şart

[params]
  # Locks the theme to dark mode by default
  defaultTheme = "dark"
  
  # Aesthetic settings for content
  ShowReadingTime = true
  ShowCodeCopyButtons = true # Adds a copy button to code blocks (Most important!)
  ShowBreadCrumbs = true
  
  # Enables the profile mode on the home page
  [params.profileMode]
    enabled = false
  [params.homeInfoParams]
    title = "0xGently"
    subtitle = "Malware Analysis | Reverse Engineering | CTI"
    imageUrl = "https://avatars.githubusercontent.com/u/225085536?v=4" # You can put your own logo
    imageWidth = 150
    imageHeight = 150
    imageTitle = "0xGently"

  # Your social media and GitHub links
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/0xGently"


# Top menu settings
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 10