baseURL = 'https://0xGently.github.io/'
languageCode = 'en-us'
title = '0xGently'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"] # Arama motorunun çalışması için JSON şart

# HTML kodlarının çalışması için gereken güvenlik izni (En üstte olması daha sağlıklıdır)
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Locks the theme to dark mode by default
  defaultTheme = "dark"
  
  # Aesthetic settings for content
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  
  # Enables the profile mode on the home page
  [params.profileMode]
    enabled = false
    
  # Ana Sayfa Bilgileri (Boşluksuz tek satır yapıldı ki kod bloğuna dönüşmesin)
  [params.homeInfoParams]
    Title = "0xGently"
    Content = """<img src="https://avatars.githubusercontent.com/u/225085536?v=4" alt="0xGently" style="display: block; margin: 0 auto 15px auto; width: 140px; border-radius: 50%;">Malware Analysis | Reverse Engineering | CTI"""

  # Your social media and GitHub links
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/0xGently"

# Top menu settings
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives/"
    weight = 10
    

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 20